### ISSUE TITLE
OSM Error

### ISSUE THREAD

**Issue by 9111651** [anvaka/city-roads#72] opened 2023-07-11 18:12 UTC
Hello, an error occurred on the website:

```
TypeError: Cannot read properties of null (reading 'elements')
```

 Can you please help?
 
 I applied for countless downloads but couldn't download them. Could you please help me download the complete map of Taiwan and send it to me by email

**Comment by anvaka** [comment] 2023-07-12 03:38
Duplicate of https://github.com/anvaka/city-roads/issues/63

**Closed** 2023-07-12 03:38 UTC
